theme: jekyll-theme-dinky
title: bisturi
description: Parse binary data in a declarative way.
github:
    owner_name: Martin Di Paola
    owner_url: https://github.com/eldipa
    repository_name: bisturi
    repository_url: https://github.com/bisturi/bisturi
uprefix: bisturi
